import SocialLogin from '@/components/SocialLogin';
import React from 'react';

export const metadata = {
  title: "Login | Code Blog AI",
  description: "Generated by create next app",
};



const Login = () => {
    return (
        <div>
            <SocialLogin></SocialLogin>
        </div>
    );
};

export default Login;