import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Provider from "@/Provider/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Code Blog",
  description: "Generated by create next app",
  keywords: [
  "Code Blog",
  "Web Development",
  "JavaScript Tutorial",
  "React JS",
  "Next.js",
  "Node.js",
  "Express.js",
  "MongoDB",
  "Frontend Development",
  "Backend Development",
  "Full Stack Developer",
  "Programming Blog",
  "Coding Tips",
  "Learn JavaScript",
  "Learn React",
  "Learn Next.js",
  "Modern Web Development",
  "Web Dev Blog",
  "Developer Resources",
],
  openGraph: {
    title: "Code Blog",
   description:
  "Code Blog is your ultimate resource to learn modern web development. Explore detailed tutorials, best practices, and real-world examples on JavaScript, React, Next.js, Node.js, Express, and MongoDB. Whether you're a beginner or an advanced developer, sharpen your coding skills and stay ahead in the tech world.",

    url: "https://code-blog-2-0.vercel.app/",
    siteName: "Code Blog",
    images: [
      {
        url: "https://developer-ratul.netlify.app/assets/my-bg-02d338d3.png",
        width: 1200,
        height: 630,
        alt: "Code Blog",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Code Blog",
description:
  "Code Blog is your ultimate resource to learn modern web development. Explore detailed tutorials, best practices, and real-world examples on JavaScript, React, Next.js, Node.js, Express, and MongoDB. Whether you're a beginner or an advanced developer, sharpen your coding skills and stay ahead in the tech world.",

    images: ["https://developer-ratul.netlify.app/assets/my-bg-02d338d3.png"],
  },
  robots: {
    index: true,
    follow: true,
  },

   verification: {
    google: "Qg2pUp6Qa7gEdG4gR04MyuxABxPEx86SxtROXl-P_Po",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <Provider>
          <header>
            <NavBar></NavBar>
          </header>

          <div className="min-h-screen">
            {children}
          </div>
          <Footer></Footer>
        </Provider>
      </body>
    </html>
  );
}
